name: Publish add-to-cart-btn

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: 'v1.0.0-dev'

jobs:
  publish:
    uses: ./.github/workflows/publish-widget-template.yml
    with:
      widget-path: widgets/add-to-cart-btn
      version: ${{ github.event.inputs.version }}
