name: Publish Widget

on:
  workflow_call:
    inputs:
      widget-path:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - run: composer config version ${{ inputs.version }}
      - run: git commit -am "chore: bump $(basename "${{ inputs.widget-path }}") to v${{ inputs.version }}"
      - run: git tag "$(basename "${{ inputs.widget-path }}")-v${{ inputs.version }}"
      - run: git push origin HEAD:main --no-tags
      - run: |
          BR=release/$(basename "${{ inputs.widget-path }}")
          git subtree split --prefix="${{ inputs.widget-path }}" -b $BR
      - run: |
          REPO="https://github.com/WeAreHausTech/$(basename "${{ inputs.widget-path }}").git"
          git push $REPO $BR:main --tags
